=== gsorepo/openmetadata/openmetadata-spec/src/main/resources/json/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json
{
  "$id": "https://open-metadata.org/schema/entity/applications/marketplace/createAppMarketPlaceDefinitionReq.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CreateAppMarketPlaceDefinitionReq",
  "javaType": "org.openmetadata.schema.entity.app.CreateAppMarketPlaceDefinitionReq",
  "javaInterfaces": ["org.openmetadata.schema.CreateEntity"],
  "description": "This schema defines the applications for Open-Metadata.",
  "type": "object",
  "properties": {
    "name": {
      "description": "Name of the Application.",
      "$ref": "../../../type/basic.json#/definitions/entityName"
    },
    "displayName": {
      "description": "Display Name for the application.",
      "type": "string"
    },
    "description": {
      "description": "Description of the Application.",
      "$ref": "../../../type/basic.json#/definitions/markdown"
    },
    "features": {
      "description": "Features of the Application.",
      "$ref": "../../../type/basic.json#/definitions/markdown"
    },
    "owner": {
      "description": "Owner of this workflow.",
      "$ref": "../../../type/entityReference.json",
      "default": null
    },
    "developer": {
      "description": "Developer For the Application.",
      "type": "string"
    },
    "developerUrl": {
      "description": "Url for the developer",
      "type": "string"
    },
    "privacyPolicyUrl": {
      "description": "Privacy Policy for the developer",
      "type": "string"
    },
    "supportEmail": {
      "description": "Support Email for the application",
      "type": "string"
    },
    "className": {
      "description": "Full Qualified ClassName for the the application",
      "type": "string"
    },
    "appType": {
      "description": "This schema defines the type of application.",
      "$ref": "../app.json#/definitions/appType"
    },
    "scheduleType": {
      "description": "This schema defines the Schedule Type of Application.",
      "$ref": "../app.json#/definitions/scheduleType"
    },
    "permission": {
      "description": "Permission used by Native Applications.",
      "$ref": "../app.json#/definitions/permissions"
    },
    "runtime": {
      "description": "If app type is live, user can provide additional runtime context.",
      "$ref": "../app.json#/definitions/executionContext"
    },
    "appConfiguration": {
      "description": "Application Configuration object."
    },
    "appLogoUrl": {
      "description": "Application Logo Url.",
      "type": "string",
      "format": "uri"
    },
    "appScreenshots": {
      "description": "Application Screenshots.",
      "type": "array",
      "items":{
        "type": "string"
      },
      "uniqueItems": true
    }
  },
  "additionalProperties": false,
  "required": ["name", "appType", "className", "scheduleType", "permission"]
}

=== gsorepo/openmetadata/openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/AutoPIIApplication.json
{
  "name": "AutoPIIApplication",
  "displayName": "Auto PII",
  "description": "Use NLP models to automatically tag PII information",
  "features": "Auto tag PII information in your tables' columns",
  "appType": "external",
  "appScreenshots": [
    "AutoPIIApplication.png"
  ],
  "developer": "Collate Inc.",
  "developerUrl": "https://www.getcollate.io",
  "privacyPolicyUrl": "https://www.getcollate.io",
  "supportEmail": "support@getcollate.io",
  "scheduleType": "Scheduled",
  "permission": "All",
  "className": "org.openmetadata.service.apps.bundles.pii.AutoPIIApplication",
  "runtime": {
    "enabled": "true"
  },
  "appConfiguration": {
    "sourcePythonClass": "metadata.applications.pii.PIIApp",
    "config": {
      "confidenceLevel": 80
    }
  }
}

=== gsorepo/openmetadata/openmetadata-service/src/main/resources/json/data/appMarketPlaceDefinition/SearchIndexingApplication.json
{
  "name": "SearchIndexingApplication",
  "displayName": "Search Indexing Application",
  "description": "Search Reindexing Application",
  "appType": "internal",
  "developer": "Collate Inc.",
  "developerUrl": "https://www.getcollate.io",
  "privacyPolicyUrl": "https://www.getcollate.io",
  "supportEmail": "support@getcollate.io",
  "scheduleType": "Scheduled",
  "permission": "All",
  "className": "org.openmetadata.service.apps.bundles.searchIndex.SearchIndexApp",
  "runtime": {
    "enabled": "true"
  },
  "appConfiguration": {
    "entities": [
      "table",
      "dashboard",
      "topic",
      "pipeline",
      "searchIndex",
      "user",
      "team",
      "glossaryTerm",
      "mlmodel",
      "tag",
      "classification",
      "query",
      "container",
      "database",
      "databaseSchema",
      "testCase",
      "testSuite",
      "chart",
      "dashboardDataModel",
      "databaseService",
      "messagingService",
      "dashboardService",
      "pipelineService",
      "mlmodelService",
      "searchService",
      "entityReportData",
      "webAnalyticEntityViewReportData",
      "webAnalyticUserActivityReportData",
      "domain",
      "storedProcedure",
      "dataProduct"
    ],
    "recreateIndex": "false",
    "batchSize": "100",
    "searchIndexMappingLanguage": "EN"
  }
}
